name: Publish
on:
    workflow_run:
        workflows: [Build]
        branches: [main]
        types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write
    id-token: write

defaults:
    run:
        shell: bash

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.10.0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'pnpm'
                  registry-url: 'https://registry.npmjs.org'

            - run: pnpm install --frozen-lockfile
            - name: 'authenticate with GH package registry'
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
